# Generated by Django 5.2 on 2025-05-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suspected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regs_no', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('charges', models.TextField()),
            ],
        ),
    ]
