# Generated by Django 5.2 on 2025-05-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PARK_EYE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regs_no', models.CharField(max_length=20)),
                ('in_date_time', models.DateTimeField(auto_now_add=True)),
                ('out_date_time', models.DateTimeField(blank=True, null=True)),
                ('in_parking', models.BooleanField(default=True)),
            ],
        ),
    ]
