# Generated by Django 5.2 on 2025-05-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PARK_EYE', '0003_remove_suspected_charges_remove_suspected_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
