# Generated by Django 5.2 on 2025-05-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PARK_EYE', '0004_police'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='police',
            name='location',
        ),
        migrations.AddField(
            model_name='police',
            name='locations',
            field=models.ManyToManyField(to='PARK_EYE.location'),
        ),
    ]
