# Generated by Django 5.2.6 on 2025-09-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PARK_EYE', '0006_vehiclerecord_slot_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police',
            name='locations',
            field=models.ManyToManyField(related_name='police_officers', to='PARK_EYE.location'),
        ),
    ]
