# Generated by Django 5.2.6 on 2025-09-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PARK_EYE', '0007_alter_police_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerecord',
            name='suspected',
            field=models.BooleanField(default=False),
        ),
    ]
