# Generated by Django 5.2.6 on 2025-09-07 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PARK_EYE', '0009_parking_vehiclerecord_parking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclerecord',
            name='parking',
        ),
    ]
