# Generated by Django 5.2.6 on 2025-09-07 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PARK_EYE', '0010_remove_vehiclerecord_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerecord',
            name='parking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='PARK_EYE.parking'),
        ),
    ]
