# Generated by Django 5.2.6 on 2025-09-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PARK_EYE', '0013_alter_police_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police',
            name='locations',
            field=models.ManyToManyField(related_name='police_officers', to='PARK_EYE.parking'),
        ),
    ]
