# Generated by Django 5.2.6 on 2025-09-05 06:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suspected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regs_no', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('crime_attempted', models.CharField(max_length=255, null=True)),
                ('spotted_location', models.CharField(max_length=255, null=True)),
                ('found_location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_founded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regs_no', models.CharField(max_length=20)),
                ('in_date_time', models.DateTimeField(blank=True, null=True)),
                ('out_date_time', models.DateTimeField(blank=True, null=True)),
                ('in_parking', models.BooleanField(default=True)),
                ('slot_position', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('locations', models.ManyToManyField(to='api.location')),
            ],
        ),
    ]
