# Generated by Django 5.2.6 on 2025-09-05 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='police',
            name='locations',
        ),
        migrations.DeleteModel(
            name='Suspected',
        ),
        migrations.DeleteModel(
            name='VehicleRecord',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Police',
        ),
    ]
